// Remplissage automatique PAR IA des objectifs hebdomadaires d'une période, à
// partir du texte de son grand objectif périodique (mainGoalText) — chantier
// cadré par Emilien le 26 septembre 2026 (discussion C, Objectifs — Logique
// métier ; cadrage produit initial dans la discussion A — Offre1, reconfirmé
// gratuit le même jour).
//
// ⚠️ Renversement d'une règle verrouillée antérieure — à noter pour la
// traçabilité : le commentaire d'en-tête de goals.js (12 septembre 2026,
// règle 2) affirmait « Ce fichier [goals.js] ne décompose JAMAIS un grand
// objectif en objectifs hebdomadaires — la génération/optimisation
// automatique d'un plan est le différenciateur de l'offre payante MANAGER. »
// Emilien a explicitement reconfirmé le 26 septembre 2026 que ce remplissage
// devient une fonctionnalité GRATUITE, hors Offre1 — voir l'annotation posée
// dans goals.js à cet endroit. goals.js lui-même reste inchangé (aucune
// décomposition n'y est codée) : c'est CE fichier, séparé, qui porte le
// mécanisme — même séparation de responsabilité que goalsauto.js (Offre1,
// déterministe) vis-à-vis de goals.js (planning manuel pur).
//
// Pourquoi un fichier séparé de goalsauto.js : goalsauto.js doit rester SANS
// aucune dépendance IA (son propre en-tête : « jamais un appel à une IA »,
// texte toujours composé par concaténation des libellés déjà écrits par
// l'utilisateur). Ici au contraire, décomposer un objectif périodique en
// objectifs hebdomadaires cohérents est un problème de compréhension de
// LANGAGE (un texte libre à interpréter et décliner dans le temps), pas de
// répartition de données déjà structurées — ça justifie un appel IA, avec
// son propre fichier plutôt que de mélanger les deux moteurs.
//
// Patron repris de server/lib/offerdelivery.js (seul autre fichier de ce
// projet qui appelle l'API Messages directement, hors chemins IA de
// classification/estimation déjà existants) : UN SEUL appel IA par
// déclenchement, sortie JSON strictement contrainte, plafonds re-validés
// côté serveur après réponse (jamais fait confiance à l'IA pour respecter
// une limite qu'elle pourrait dépasser).
//
// Règle produit rappelée ici car elle s'applique intégralement : « L'IA
// propose, ne décide jamais à la place de l'utilisateur » — et, verbatim
// dans la demande d'Emilien : « Ne jamais écraser un objectif déjà saisi ».
// Concrètement : seules les semaines ENTIÈREMENT VIDES (aucune ligne
// goal_weekly active du tout — ni écrite par l'utilisateur, ni déjà
// composée par le moteur Offre1/goalsauto.js) reçoivent une proposition ;
// une semaine déjà remplie, quelle qu'en soit l'origine, n'est JAMAIS
// touchée. L'appel IA n'a même lieu que s'il reste au moins une semaine
// vide — sinon aucun coût engagé.
//
// Colonne autoGenerated (goal_weekly) : vérifiée avant réutilisation, comme
// demandé — NON réutilisée. Elle porte un sens déjà pris et différent (« composé
// par le moteur Offre1 à partir de tâches Sous-projets regroupées », voir
// l'en-tête de goalsauto.js) : un objectif autoGenerated=1 n'est PAS un texte
// interprété par une IA, c'est une concaténation déterministe de libellés
// déjà écrits par l'utilisateur ailleurs. Conflater les deux sous un seul
// indicateur ferait perdre cette distinction (utile au moins pour un futur
// affichage différencié — badge « généré par IA » vs « regroupé
// automatiquement »). Nouvelle colonne dédiée : goal_weekly.aiGenerated (voir
// migration dans server/db.js, juste après celle d'autoGenerated).
//
// Déclenchement : PAS appelé depuis l'intérieur de goals.js#setMainGoal (qui
// doit rester pur/synchrone, sans import IA — même raison que la séparation
// de fichier ci-dessus). Appelé depuis server/routes/goals.js, juste après
// l'écriture synchrone de goals.setMainGoal, en « fire-and-forget » (jamais
// awaité) : la réponse HTTP de l'utilisateur part immédiatement, la
// proposition IA arrive en tâche de fond et devient visible la prochaine
// fois que la semaine concernée est ouverte — même logique de visibilité non
// interruptive que la suggestion cross-secteur (voir point de coordination
// ci-dessous).
//
// Point de coordination (tranché ici, demande explicite d'Emilien du 26
// septembre 2026) : le même déclencheur (setMainGoal) porte AUSSI le futur
// moteur d'inférence cross-secteur (« Coordination inter-secteurs »,
// noesis-timetracker-coordination-inter-secteurs.md, brief 1 — pas encore
// codé). Décision : SÉQUENCEMENT EXPLICITE, jamais deux hooks indépendants
// lancés en parallèle depuis la route. Ce remplissage hebdomadaire (ce
// fichier) s'exécute EN PREMIER — il est le plus directement lié au texte
// qui vient d'être écrit, et le plus étroit/rapide des deux. Le moteur
// cross-secteur (une fois codé) sera chaîné APRÈS, via un .then() sur la
// promesse renvoyée par generateForPeriod ci-dessous, dans
// server/routes/goals.js — jamais un second .catch() indépendant posé en
// parallèle. Raison : les deux appellent l'API Messages pour le MÊME
// événement ; les enchaîner évite deux appels IA concurrents pour un même
// setMainGoal (hygiène de débit/coût) et garde un ordre déterministe et
// unique pour le débogage futur. Les deux mécanismes n'écrivent cela dit
// jamais sur les mêmes lignes (celui-ci : goal_weekly de LA MÊME catégorie ;
// l'autre : suggestion en attente ciblant une AUTRE catégorie/secteur) — le
// séquencement est une précaution de coût/lisibilité, pas une nécessité de
// cohérence des données.

const db = require('../db');
const goals = require('./goals');

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';
const ANTHROPIC_MODEL = process.env.ANTHROPIC_MODEL || 'claude-sonnet-5';
// Même plafond que PUT /activities/:id/goals/periods/:periodNumber/weekly/:weekIndex
// (server/routes/goals.js) — un objectif hebdomadaire composé par l'IA n'a
// pas droit à une limite différente de celle posée à l'utilisateur.
const MAX_WEEKLY_TEXT_LENGTH = 300;

function aiConfigured() {
  return !!process.env.ANTHROPIC_API_KEY;
}

// Semaines (1..WEEKS_PER_PERIOD) de cette période n'ayant AUCUNE ligne
// goal_weekly active (carriedOverFromId IS NULL) — qu'elle ait été écrite par
// l'utilisateur ou composée par goalsauto.js, peu importe : dans les deux cas
// la semaine n'est pas vide et ne doit jamais être proposée par l'IA.
function emptyWeekIndexes(periodId) {
  const filled = new Set(
    goals.weeklyForPeriod(periodId)
      .filter((w) => w.carriedOverFromId == null)
      .map((w) => w.weekIndex)
  );
  const empty = [];
  for (let w = 1; w <= goals.WEEKS_PER_PERIOD; w += 1) {
    if (!filled.has(w)) empty.push(w);
  }
  return empty;
}

const SYSTEM_PROMPT = `Tu aides à planifier les objectifs d'une entreprise sur Noèsis. On te donne le grand objectif d'une période de 4 semaines (un pôle ou secteur d'activité) et, éventuellement, le texte déjà écrit pour certaines semaines de cette même période. Décline le grand objectif en objectifs hebdomadaires CONCRETS et ACTIONNABLES uniquement pour les numéros de semaine demandés (jamais les autres), cohérents entre eux et avec les semaines déjà écrites si il y en a.
Réponds UNIQUEMENT avec un objet JSON de cette forme exacte, sans texte ni Markdown autour :
{"weeklyGoals":[{"weekIndex":N,"text":"..."}]}
Contraintes : un objet par numéro de semaine demandé, jamais un numéro non demandé ; chaque "text" fait moins de ${MAX_WEEKLY_TEXT_LENGTH} caractères, en français, une phrase d'action concrète (pas une reformulation vague du grand objectif).`;

async function callAi(payload, requestedWeeks) {
  const res = await fetch(ANTHROPIC_API_URL, {
    method: 'POST',
    headers: {
      'x-api-key': process.env.ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: ANTHROPIC_MODEL,
      max_tokens: 1024,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: JSON.stringify(payload) }],
    }),
  });
  if (!res.ok) {
    let detail = '';
    try {
      const body = await res.json();
      detail = body && body.error && body.error.message ? body.error.message : '';
    } catch (err) {
      // réponse non-JSON — pas d'information supplémentaire
    }
    throw new Error(`L'IA a refusé de générer les objectifs hebdomadaires (HTTP ${res.status})${detail ? ' : ' + detail : ''}.`);
  }
  const body = await res.json();
  const text = (body.content || []).map((block) => block.text || '').join('');
  return parseWeeklyGoals(text, requestedWeeks);
}

// Validation stricte : ne fait JAMAIS confiance à l'IA pour respecter les
// plafonds ou pour ne proposer que les semaines demandées — les deux sont
// re-vérifiés ici (même discipline que offerdelivery.js#parsePlan).
function parseWeeklyGoals(text, requestedWeeks) {
  requestedWeeks = requestedWeeks || [];
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (err) {
    throw new Error("Réponse de l'IA illisible (JSON invalide).");
  }
  const raw = Array.isArray(parsed.weeklyGoals) ? parsed.weeklyGoals : [];
  const allowed = new Set(requestedWeeks);
  const seen = new Set();
  const out = [];
  raw.forEach((entry) => {
    const weekIndex = Number(entry && entry.weekIndex);
    if (!allowed.has(weekIndex) || seen.has(weekIndex)) return; // hors périmètre demandé ou doublon : ignoré, jamais une erreur bloquante
    const clean = typeof entry.text === 'string' ? entry.text.trim().slice(0, MAX_WEEKLY_TEXT_LENGTH) : '';
    if (!clean) return;
    seen.add(weekIndex);
    out.push({ weekIndex, text: clean });
  });
  return out;
}

// Point d'entrée — voir le commentaire d'en-tête pour le déclenchement
// (fire-and-forget depuis server/routes/goals.js) et le séquencement avec le
// futur moteur cross-secteur. Ne lève JAMAIS : un échec IA laisse simplement
// les semaines vides, comme si l'utilisateur ne les avait pas encore
// remplies — jamais bloquant pour la requête HTTP qui a déjà répondu au
// moment où ceci s'exécute.
async function generateForPeriod(activityId, userId, category, periodNumber) {
  try {
    if (!aiConfigured()) return { skipped: 'ai-not-configured' };

    const period = db.prepare('SELECT * FROM goal_periods WHERE activityId = ? AND category = ? AND periodNumber = ?')
      .get(activityId, category, periodNumber);
    if (!period || !period.mainGoalText || !period.mainGoalText.trim()) return { skipped: 'no-main-goal' };

    const emptyWeeks = emptyWeekIndexes(period.id);
    if (!emptyWeeks.length) return { skipped: 'no-empty-week' };

    const catInfo = goals.categoriesForActivity(activityId).find((c) => c.key === category)
      || { label: goals.categoryLabelFor(activityId, category), description: '' };
    const alreadyWritten = goals.weeklyForPeriod(period.id)
      .filter((w) => w.carriedOverFromId == null && w.text && w.text.trim())
      .map((w) => ({ weekIndex: w.weekIndex, text: w.text }));

    const proposals = await callAi({
      category: { label: catInfo.label, description: catInfo.description || '' },
      period: { periodNumber, startDate: period.startDate, endDate: period.endDate },
      mainGoalText: period.mainGoalText,
      weeksAlreadyWritten: alreadyWritten,
      weeksToFill: emptyWeeks,
    }, emptyWeeks);

    let written = 0;
    const createdAt = new Date().toISOString();
    proposals.forEach((p) => {
      // Re-vérifié juste avant écriture (protection contre une saisie
      // manuelle survenue pendant l'aller-retour IA) — « ne jamais écraser
      // un objectif déjà saisi » s'applique aussi à ce cas de course.
      const stillEmpty = !db.prepare('SELECT 1 FROM goal_weekly WHERE periodId = ? AND weekIndex = ? AND carriedOverFromId IS NULL')
        .get(period.id, p.weekIndex);
      if (!stillEmpty) return;
      const estimate = goals.estimateForGoal(activityId, category, 'weekly', p.text);
      db.prepare(`
        INSERT INTO goal_weekly
          (periodId, weekIndex, text, estimateMinutes, estimateSource, estimateConfidence, aiGenerated, createdAt)
        VALUES (?, ?, ?, ?, ?, ?, 1, ?)
      `).run(period.id, p.weekIndex, p.text, estimate.minutes, estimate.source, estimate.confidence, createdAt);
      written += 1;
    });

    return { written, proposed: proposals.length, emptyWeeks: emptyWeeks.length };
  } catch (err) {
    console.warn('[objectifs][remplissage IA hebdomadaire] échoué pour l\'activité ' + activityId + ' / ' + category + ' / période ' + periodNumber + ' :', err && err.message);
    return { error: true };
  }
}

module.exports = {
  MAX_WEEKLY_TEXT_LENGTH,
  emptyWeekIndexes,
  generateForPeriod,
  // Exportés pour les tests (bac à sable) uniquement.
  parseWeeklyGoals,
};
