// Moteur d'auto-planification Sous-projets → Objectifs — chantier Objectifs
// — C (15 septembre 2026, cadré avec Emilien — voir
// noesis-timetracker-objectifs.md et noesis-timetracker-chantiers-en-cours.md).
//
// Rôle : les tâches Sous-projets rattachées à une catégorie Objectifs
// (sub_projects.goalCategory) sont automatiquement regroupées par
// ressemblance et casées dans le planning hebdomadaire (goal_weekly,
// autoGenerated = 1) du membre PRÉVU pour les faire
// (sub_project_items.plannedUserId), en respectant sa capacité hebdomadaire
// habituelle.
//
// ⚠️ GRATUIT, PAS GATÉ — clarifié avec Emilien le 15 septembre 2026 (soir),
// APRÈS que la « vraie » Offre 1 a été concrétisée et documentée le même
// jour dans noesis-timetracker-offre1-definition.md : un abonnement payant
// distinct (20 $/mois/activité), porté par la discussion A, avec ses propres
// formulaires de diagnostic et une génération de feuille de route par appel
// à l'IA (Claude). CE moteur-ci — regroupement déterministe des tâches
// Sous-projets déjà écrites par l'utilisateur, sans IA ni Stripe — N'EST PAS
// cette Offre 1 : c'est une fonctionnalité gratuite séparée. Le gating
// `activity_offre1` posé plus tôt le même jour reposait sur une confusion
// entre les deux, corrigée par Emilien avant tout usage réel. La table
// `activity_offre1` et les fonctions isOffre1Active/activateOffre1/
// deactivateOffre1 restent en base et exportées (vestige inoffensif, sans
// aucune migration à refaire) mais ne sont PLUS appelées par ce moteur —
// scripts/activate-offre1.js n'a donc plus aucun effet utile ici.
//
// Fichier SÉPARÉ de server/lib/goals.js plutôt que d'y ajouter ce moteur :
// goals.js reste le planning « manuel » historique, ce fichier est la seule
// pièce qui écrit AUTOMATIQUEMENT dans goal_weekly.
//
// N'écrit JAMAIS un texte inventé de toutes pièces : le texte d'un objectif
// généré est toujours composé à partir des libellés déjà écrits par
// l'utilisateur dans Sous-projets (regroupement/concaténation), jamais une
// reformulation libre — ni, a fortiori, un appel à une IA.

const db = require('../db');
const goals = require('./goals');

// Fenêtre glissante utilisée pour estimer la capacité hebdomadaire d'un
// membre — cadré avec Emilien le 15 septembre 2026 (8 dernières semaines
// TERMINÉES). En repli, sans historique pour ce membre dans cette catégorie :
// moyenne des 8 dernières semaines glissantes (calendaires) de l'ENSEMBLE des
// membres actifs de l'activité (même cadrage).
const RECENT_WEEKS_WINDOW = 8;

// Même seuil de similarité que estimateForGoal dans goals.js, pour rester
// cohérent avec le reste du moteur d'estimation.
const SIMILARITY_THRESHOLD = 0.15;

// Dupliqué délibérément depuis goals.js (qui le duplique lui-même depuis
// duereminders.js) plutôt qu'exporté : une fonction de date d'une ligne ne
// justifie pas un export de plus — même raisonnement que le commentaire en
// tête de goals.js.
function todayLocal() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate());
}

// ---------------------------------------------------------------------------
// Vestige : activation manuelle d'un gating par activité (voir
// scripts/activate-offre1.js) — PLUS UTILISÉ par ce moteur depuis le 15
// septembre 2026 (soir), voir l'avertissement en tête de fichier. Laissé en
// place (table `activity_offre1` incluse) au cas où un futur chantier
// business (ex. Paiement et abonnements) voudrait un gating similaire pour
// autre chose — aucun effet sur reorganizeCategory/onSubProjectItemChanged
// ci-dessous.

function isOffre1Active(activityId) {
  return !!db.prepare('SELECT 1 FROM activity_offre1 WHERE activityId = ?').get(activityId);
}

function activateOffre1(activityId) {
  if (isOffre1Active(activityId)) return;
  db.prepare('INSERT INTO activity_offre1 (activityId, activatedAt) VALUES (?, ?)')
    .run(activityId, new Date().toISOString());
}

function deactivateOffre1(activityId) {
  db.prepare('DELETE FROM activity_offre1 WHERE activityId = ?').run(activityId);
}

// ---------------------------------------------------------------------------
// Capacité hebdomadaire d'un membre, pour une (activité, catégorie) — voir
// le cadrage en tête de fichier.

// Minutes réelles chronométrées, semaine par semaine, sur les dernières
// semaines TERMINÉES (bornes goal_weekly, pas calendaires) où `userId` avait
// un objectif hebdomadaire assigné dans cette (activité, catégorie).
function recentWeeklyMinutesForUser(activityId, category, userId, limit) {
  const rows = db.prepare(`
    SELECT p.startDate AS periodStart, w.weekIndex AS weekIndex
    FROM goal_weekly w
    JOIN goal_periods p ON p.id = w.periodId
    WHERE p.activityId = ? AND p.category = ? AND w.assignedUserId = ?
    ORDER BY p.periodNumber DESC, w.weekIndex DESC
  `).all(activityId, category, userId);

  const today = todayLocal();
  const minutes = [];
  for (const r of rows) {
    if (minutes.length >= limit) break;
    const bounds = goals.weekBounds(r.periodStart, r.weekIndex);
    if (bounds.end >= today) continue; // semaine pas encore terminée
    minutes.push(Math.round(goals.actualSecondsForRange(activityId, bounds.start, bounds.end) / 60));
  }
  return minutes;
}

// Repli sans historique (cadré avec Emilien) : moyenne, sur les 8 dernières
// semaines calendaires glissantes, du temps réel chronométré sur l'activité
// ENTIÈRE (le chrono n'est jamais scindé par catégorie dans ce projet — voir
// actualSecondsForRange dans goals.js), divisé par le nombre de membres
// actifs — une approximation de « ce que fait en moyenne un membre par
// semaine sur cette activité », faute de mieux pour un membre tout juste
// assigné.
function fallbackCapacityMinutes(activityId) {
  const today = todayLocal();
  const start = goals.addDays(today, -RECENT_WEEKS_WINDOW * 7);
  const end = goals.addDays(today, -1);
  const totalMinutes = Math.round(goals.actualSecondsForRange(activityId, start, end) / 60);
  const memberCount = db.prepare('SELECT COUNT(*) AS n FROM activity_members WHERE activityId = ?').get(activityId).n || 1;
  return Math.max(1, Math.round(totalMinutes / RECENT_WEEKS_WINDOW / memberCount));
}

function capacityMinutesForMember(activityId, category, userId) {
  const history = recentWeeklyMinutesForUser(activityId, category, userId, RECENT_WEEKS_WINDOW);
  if (history.length) {
    return Math.max(1, Math.round(history.reduce((s, m) => s + m, 0) / history.length));
  }
  return fallbackCapacityMinutes(activityId);
}

// ---------------------------------------------------------------------------
// Regroupement des tâches en attente, par ressemblance de libellé — réutilise
// tokenize/jaccard de goals.js (même moteur que l'estimation par similarité).

function clusterPendingItems(items) {
  // Regroupement glouton : chaque tâche rejoint le premier groupe existant
  // dont elle dépasse le seuil de similarité avec l'ensemble des mots déjà
  // vus dans ce groupe, sinon ouvre un nouveau groupe. Pas de recherche
  // combinatoire du meilleur découpage : le volume traité par passage (tâches
  // ajoutées entre deux placements) reste petit, et un résultat imparfait
  // mais stable vaut mieux qu'un calcul coûteux à chaque tâche cochée.
  const groups = [];
  items.forEach((item) => {
    const tokens = new Set(goals.tokenize(item.label));
    const target = groups.find((g) => goals.jaccard(tokens, g.tokens) > SIMILARITY_THRESHOLD);
    if (target) {
      tokens.forEach((t) => target.tokens.add(t));
      target.items.push(item);
    } else {
      groups.push({ tokens, items: [item] });
    }
  });
  return groups.map((g) => g.items);
}

// Texte gabarit : concatène les libellés déjà écrits par l'utilisateur,
// jamais une reformulation inventée (voir l'avertissement en tête de
// fichier).
function buildGroupText(items) {
  return items.map((i) => i.label).join(' + ');
}

// ---------------------------------------------------------------------------
// Placement dans le planning — un objectif hebdomadaire par semaine (règle
// historique de goals.js), rempli dans l'ordre depuis le premier créneau
// libre ; plusieurs petits groupes qui tiennent ensemble sous la capacité
// d'une même semaine sont fusionnés dans le même objectif, un groupe qui à
// lui seul dépasse la capacité est quand même placé seul (jamais scindé — un
// objectif déjà regroupé n'est jamais fragmenté).

function pendingItemsForCategory(activityId, category) {
  return db.prepare(`
    SELECT i.id, i.label, i.plannedUserId, i.subProjectId
    FROM sub_project_items i
    JOIN sub_projects sp ON sp.id = i.subProjectId
    WHERE sp.activityId = ? AND sp.goalCategory = ? AND i.goalWeeklyId IS NULL AND i.done = 0
      AND (sp.closesAt IS NULL OR sp.closesAt >= date('now','localtime'))
    ORDER BY i.position ASC, i.id ASC
  `).all(activityId, category);
}

// Premier créneau (période, semaine) libre à partir de (periodNumber,
// weekIndex) — même logique de recherche que carryOverWeekly dans goals.js
// pour le report automatique, réécrite ici pour partir d'un point de départ
// arbitraire plutôt que d'un objectif précis à reporter.
function nextFreeSlot(activityId, category, planStartDate, periodNumber, weekIndex) {
  let pn = periodNumber;
  let wi = weekIndex;
  for (;;) {
    const period = goals.ensurePeriodRow(activityId, category, pn, planStartDate);
    const occupied = db.prepare('SELECT 1 FROM goal_weekly WHERE periodId = ? AND weekIndex = ?').get(period.id, wi);
    if (!occupied) return { period, weekIndex: wi };
    wi += 1;
    if (wi > goals.WEEKS_PER_PERIOD) {
      pn += 1;
      wi = 1;
    }
  }
}

function reorganizeForMember(activityId, category, userId, items) {
  const plan = goals.ensurePlan(activityId, category);
  const capacityMinutes = capacityMinutesForMember(activityId, category, userId);

  const groups = clusterPendingItems(items).map((groupItems) => {
    const text = buildGroupText(groupItems);
    const estimate = goals.estimateForGoal(activityId, category, 'weekly', text);
    return {
      items: groupItems,
      text,
      estimate,
      // Aucun historique de similarité (source 'none') : on suppose une
      // semaine pleine plutôt que 0 minute, pour ne pas sous-caser.
      minutes: estimate.minutes != null ? estimate.minutes : capacityMinutes,
    };
  });

  let periodNumber = goals.periodNumberForDate(plan.startDate, todayLocal());
  let weekIndex = 1;
  let placedCount = 0;
  let bucket = [];
  let bucketMinutes = 0;

  const flush = () => {
    if (!bucket.length) return;
    const slot = nextFreeSlot(activityId, category, plan.startDate, periodNumber, weekIndex);
    const text = bucket.map((g) => g.text).join(' / ');
    const minutes = bucket.reduce((s, g) => s + g.minutes, 0);
    // Source/confiance : celles du premier groupe du lot — un détail
    // d'affichage (badge « estimation »), jamais une valeur qui conditionne
    // le placement lui-même.
    const source = bucket[0].estimate.source;
    const confidence = Math.min(...bucket.map((g) => (g.estimate.confidence != null ? g.estimate.confidence : 1)));
    const createdAt = new Date().toISOString();
    const info = db.prepare(`
      INSERT INTO goal_weekly
        (periodId, weekIndex, text, estimateMinutes, estimateSource, estimateConfidence, assignedUserId, autoGenerated, createdAt)
      VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)
    `).run(slot.period.id, slot.weekIndex, text, minutes, source, confidence, userId, createdAt);
    const weeklyId = Number(info.lastInsertRowid);

    const markPlaced = db.prepare('UPDATE sub_project_items SET goalWeeklyId = ? WHERE id = ?');
    bucket.forEach((g) => g.items.forEach((it) => markPlaced.run(weeklyId, it.id)));
    placedCount += bucket.reduce((s, g) => s + g.items.length, 0);

    periodNumber = slot.period.periodNumber;
    weekIndex = slot.weekIndex + 1;
    if (weekIndex > goals.WEEKS_PER_PERIOD) {
      periodNumber += 1;
      weekIndex = 1;
    }
    bucket = [];
    bucketMinutes = 0;
  };

  groups.forEach((g) => {
    if (bucket.length && bucketMinutes + g.minutes > capacityMinutes) flush();
    bucket.push(g);
    bucketMinutes += g.minutes;
  });
  flush();

  return placedCount;
}

// Point d'entrée : reclasse toutes les tâches en attente d'une (activité,
// catégorie), par membre PRÉVU. Gratuit, jamais gaté (voir l'avertissement en
// tête de fichier) — ne fait rien seulement si la catégorie n'est pas valide
// pour cette activité, jamais une erreur : un appelant (routes/subprojects.js)
// n'a pas à vérifier cette condition lui-même à chaque fois.
function reorganizeCategory(activityId, category) {
  if (!activityId || !category) return { processed: 0 };
  if (!goals.isValidCategoryForActivity(activityId, category)) return { processed: 0 };

  const pending = pendingItemsForCategory(activityId, category);
  const byMember = new Map();
  pending.forEach((item) => {
    // Une tâche sans membre prévu ne peut pas être casée (pas de capacité à
    // dimensionner) — elle reste en attente jusqu'à ce qu'un plannedUserId
    // lui soit donné (PUT /api/sub-project-items/:id).
    if (!item.plannedUserId) return;
    if (!byMember.has(item.plannedUserId)) byMember.set(item.plannedUserId, []);
    byMember.get(item.plannedUserId).push(item);
  });

  let processed = 0;
  byMember.forEach((items, userId) => {
    processed += reorganizeForMember(activityId, category, userId, items);
  });
  return { processed };
}

// Appelé depuis server/routes/subprojects.js après création/modification
// d'une tâche — jamais bloquant pour la réponse HTTP : une erreur inattendue
// du moteur ne doit jamais empêcher l'utilisateur de cocher sa tâche.
function onSubProjectItemChanged(activityId, category) {
  try {
    return reorganizeCategory(activityId, category);
  } catch (err) {
    console.warn('[objectifs][offre1] auto-planification échouée pour l\'activité ' + activityId + ' / ' + category + ' :', err && err.message);
    return { processed: 0 };
  }
}

module.exports = {
  RECENT_WEEKS_WINDOW,
  isOffre1Active,
  activateOffre1,
  deactivateOffre1,
  capacityMinutesForMember,
  reorganizeCategory,
  onSubProjectItemChanged,
};
